# Generated by Django 4.1 on 2023-09-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobApplication", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="applications",
            constraint=models.UniqueConstraint(
                fields=("applicant", "job"), name="unique_composite_key"
            ),
        ),
    ]
