# Generated by Django 4.1 on 2023-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobApplication", "0002_applications_unique_composite_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="resume_text",
            field=models.TextField(default="No Resume", max_length=10000),
        ),
    ]
