# Generated by Django 4.1 on 2023-09-25 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jobApplication", "0003_applications_resume_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
